name: Build

on:
  workflow_dispatch:

jobs:
  build:
    # Set the agent to run on
    runs-on: self-hosted

    strategy:
        matrix:
          node-version: [20.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM Install
        run: |
            npm install
